from __future__ import annotations

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)

def export_day_pdf(
    pdf_dir: str,
    user_id: int,
    date_str: str,
    totals: dict[str, float],
    lang: str = "ru",
) -> str:
    ensure_dir(pdf_dir)
    filename = f"kbju_{user_id}_{date_str}.pdf"
    filepath = os.path.join(pdf_dir, filename)

    c = canvas.Canvas(filepath, pagesize=A4)
    w, h = A4

    title = "Отчёт КБЖУ за день" if lang == "ru" else "Daily macros report"
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h - 60, title)

    c.setFont("Helvetica", 12)
    c.drawString(50, h - 90, ("Дата: " if lang == "ru" else "Date: ") + date_str)
    c.drawString(50, h - 120, ("Калории: " if lang == "ru" else "Calories: ") + f"{totals['kcal']:.0f} kcal")
    c.drawString(50, h - 145, ("Белки: " if lang == "ru" else "Protein: ") + f"{totals['p']:.1f} g")
    c.drawString(50, h - 170, ("Жиры: " if lang == "ru" else "Fat: ") + f"{totals['f']:.1f} g")
    c.drawString(50, h - 195, ("Углеводы: " if lang == "ru" else "Carbs: ") + f"{totals['c']:.1f} g")

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 40, "Generated by KБЖУ bot")

    c.showPage()
    c.save()
    return filepath
